const TRANSCRIPT_FAST_PATH_MAX_CHARS = Number(
  process.env.TRANSCRIPT_FAST_PATH_MAX_CHARS || 18000
)
const AUDIO_SUMMARY_CONCURRENCY = Math.max(
  1,
  Number(process.env.AUDIO_SUMMARY_CONCURRENCY || 2)
)
const TRANSCRIPT_SUMMARY_CONCURRENCY = Math.max(
  1,
  Number(process.env.TRANSCRIPT_SUMMARY_CONCURRENCY || 3)
)

module.exports = {
  AUDIO_SUMMARY_CONCURRENCY,
  TRANSCRIPT_FAST_PATH_MAX_CHARS,
  TRANSCRIPT_SUMMARY_CONCURRENCY,
}
